# Generated by Django 4.1 on 2022-09-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_teacher_subject_name_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('total_semester', models.IntegerField(default=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.course_master')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='std_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course_master'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject_master'),
        ),
    ]
