# Generated by Django 4.1 on 2022-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_student_std_course_teacher_subject_allocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
    ]
