# Generated by Django 4.1 on 2022-09-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_student_options_remove_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='ass_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.subject_master'),
        ),
    ]
