# Generated by Django 4.1 on 2023-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_classassignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='submission_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
