# Generated by Django 4.1 on 2023-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_studentmarks_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='is_marked',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
